Repository Flexberry/NewPlatform.Flexberry.ORM, pull requests merged in 2020-04, with the labels that each got.

#98 Merge UpdateObjects and UpdateObjectsByExtConn.
  ICSSoft.STORMNET.Business/SQLDataService/SQLDataService.UpdateObjects.cs
  ICSSoft.STORMNET.Business/SQLDataService/SQLDataService.cs
Labels: refactoring

#100 Fix DbTransactionWrapper commit and rollback over expired connections.
  ICSSoft.STORMNET.Business/SQLDataService/DbTransactionWrapper.cs
  NewPlatform.Flexberry.ORM.IntegratedTests/BaseIntegratedTest.cs
Labels: bug

#102 Test loading not stored properties
  CHANGELOG.md
  NewPlatform.Flexberry.ORM.IntegratedTests/ICSSoft.STORMNET.Business/NotStoredPropertyLoadingTests.cs
  NewPlatform.Flexberry.ORM.IntegratedTests/NewPlatform.Flexberry.ORM.IntegratedTests.csproj
  NewPlatform.Flexberry.ORM.nuspec
Labels: enhancement

#103 Fix null GetHandler or SetHandler via cache dictionary.
  ICSSoft.STORMNET.DataObject/DataObject.cs
Labels: bug

#104 Fix rethrowing exception while hadling special scenerio via UpdateObjects
  CHANGELOG.md
  ICSSoft.STORMNET.Business/SQLDataService/SQLDataService.cs
  NewPlatform.Flexberry.ORM.nuspec
Labels: bug

#106 Add test for loading not stored master
  CHANGELOG.md
  ICSSoft.STORMNET.Business/Utils/Utils.FillRowSetToDataObject.cs
  NewPlatform.Flexberry.ORM.IntegratedTests/ICSSoft.STORMNET.Business/LoadObjectTest.cs
  NewPlatform.Flexberry.ORM.Test.Objects/Страна.cs
  NewPlatform.Flexberry.ORM.nuspec
Labels: bug
