Repository Flexberry/NewPlatform.Flexberry.ORM, pull requests merged in 2021-08, with the labels that each got.

#195 Оптимизация формирования sql-запросов
  CHANGELOG.md
  ICSSoft.STORMNET.Business/SQLDataService/SQLDataService.cs
  NewPlatform.Flexberry.ORM.IntegratedTests/BaseIntegratedTest.cs
  NewPlatform.Flexberry.ORM.IntegratedTests/ICSSoft.STORMNET.Business/DataServiceSpeedTest.cs
  NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/BaseSQLDataServiceTests.cs
  NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business/SQLDataServiceGenerateSQLTests.cs
  NewPlatform.Flexberry.ORM.nuspec
Labels: enhancement, refactoring

#198 Fix Nullable<bool> isnull limit
  ICSSoft.STORMNET.Business.LINQProvider/LcsGeneratorExpressionTreeVisitorBase.cs
  NewPlatform.Flexberry.ORM.IntegratedTests/CodeGen/NewPlatform.Flexberry.ORM.Tests.crp
  NewPlatform.Flexberry.ORM.IntegratedTests/CodeGen/generate-code.sh
  NewPlatform.Flexberry.ORM.IntegratedTests/SqlScripts/MssqlScript.sql
  NewPlatform.Flexberry.ORM.IntegratedTests/SqlScripts/OracleScript.sql
  NewPlatform.Flexberry.ORM.IntegratedTests/SqlScripts/PostgresScript.sql
  NewPlatform.Flexberry.ORM.Test.Objects/ТипПороды.cs
  NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.Business.LINQProvider/LinqToLcsNullableTest.cs
Labels: bug

#199 Fix TestInvisibleViewOnAddProperty test
  ICSSoft.STORMNET.DataObject/Information.cs
  ICSSoft.STORMNET.DataObject/View.cs
  NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.DataObject/DataObjectCacheTest.cs
  NewPlatform.Flexberry.ORM.Tests/ICSSoft.STORMNET.DataObject/ViewTest.cs
Labels: refactoring
